---

- hosts: ansible
  name: "My JBoss Server Deployment"
  become: yes 
  vars:
    doc_jboss: "/opt/SP/apps"
    download_url: "https://download.jboss.org/wildfly/24.0.0.Final/wildfly-24.0.0.Final.zip"

  tasks:
  - name: JBoss Home Dir
    file: path={{doc_jboss}}/jboss state=directory

  - name: Install Default JDK 1.8 
    apt: name=default-jdk state=present

  - name: Download JBoss Zip
    get_url: url={{download_url}} dest={{doc_jboss}}/wildfly-24.0.0.Final.zip mode=0755

  - name: Extract JBoss Zip
    command: "unzip {{doc_JBoss}}/wildfly-24.0.0.Final.zip -C {{doc_jboss}}/jboss --strip-components 1"

  - name: Start JBoss App Server 
    shell: "nohup  /opt/SP/apps/jboss/wildfly-24.0.0.Final/bin/standalone.sh --admin-only"
