---

- hosts : web
  name : WebServer Setup
  become: yes
  tasks: 
  - name: Install Apache2 Package
    apt: name=apache2 state=present

  - name: Start Apache2 Service
    service: name=apache2 state=started

  - name: Index page is displayed
    copy: src=files/index.html dest=/var/www/html
  
  - name: Index page is displayed
    template: src=templates/info.j2 dest=/var/www/html/info.html


- hosts: web
  name: Kernel Check
  become: yes
  tasks:
  - name: Run Command
    command: 'uname -a' 
