---

- hosts : web
  name : WebServer Setup
  become: yes
  tasks: 
  - name: Install Apache2 Package
    apt: name=apache2 state=present

  - name: Start Apache2 Service
    service: name=apache2 state=started



- hosts: web
  name: Kernel Check
  become: yes
  tasks:
  - name: Run Command
    command: 'uname -a' 
